'use client'
import PagingRequest from '@/objects/requests/PagingRequest'
import { NEXT_PUBLIC_MAXPAGE } from '@/utils/env'
import React from 'react'
// export const metadata: Metadata = {
//     title: 'Dit me may',
//     description: 'Generated by create next app',
// }
interface Params {
    params: { id: string }
    searchParams: { [key: string]: string | string[] | undefined }
}
function about() {
    return (
        <div>
        </div>
    )
}

export default about