'use client'
import PagingRequest from '@/objects/requests/PagingRequest'
import queryString from 'query-string'
import React from 'react'
// export const metadata: Metadata = {
//     title: 'Dit me may',
//     description: 'Generated by create next app',
// }
interface Params {
    params: { id: string }
    searchParams: { [key: string]: string | string[] | undefined }
}
function about() {
    const onClick = () => {
    }
    return (
        <div>
            <button onClick={onClick}>Click</button>
        </div>
    )
}

export default about