import { Metadata } from 'next'
import React from 'react'
export const metadata: Metadata = {
    title: 'Dit me may',
    description: 'Generated by create next app',
  }
function about() {
    return (
        <div>about</div>
    )
}

export default about