export const NEXT_PUBLIC_API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
export const NEXT_PUBLIC_REQUEST_TIMEOUT = process.env.NEXT_PUBLIC_REQUEST_TIMEOUT;
export const NEXT_PUBLIC_MAXPAGE = process.env.NEXT_PUBLIC_MAXPAGE;